### ISSUE TITLE
Add fixes from maintained fork

### ISSUE THREAD

**Issue by matthewhegarty** [diff-match-patch-python/diff-match-patch#16]
Now that the base upstream repo is [read-only](https://github.com/google/diff-match-patch) there is a maintained fork [here](https://github.com/dmsnell/diff-match-patch).

The fork has some [python patches](https://github.com/dmsnell/diff-match-patch/commits/main/) which are not yet ported to this repo.

- Do you want me to add these patches?
- Do we need to change the base upstream repo?

**Comment by amyreese** [comment]
Yes, would be happy to review PRs for updating scripts/docs and porting upstream patches. 🙂
